language: generic
sudo: required
services:
  - docker

before_instal:
  - docker build -t mottigendave/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mottigendave/docker-react npm run test